name: 🧪 CI Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

permissions:
    contents: read
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🩺 Run test
              run: pnpm run test
